name: bovihpi
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython
  - hmmer
  - blast
  - clustalw
  - cd-hit
  - perl
  - libboost
  - make
  - gxx_linux-64
  - libxml2
  - wget
  - pip
  - pip:
      - numpy
      - pandas
